export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  resendApiFrom: process.env.RESEND_API_FROM ?? "onboarding@resend.dev",
  gmailUser: process.env.GMAIL_USER ?? "",
  gmailAppPassword: process.env.GMAIL_APP_PASSWORD ?? "",
  sendgridApiKey: process.env.SENDGRID_API_KEY ?? "",
  sendgridFrom: process.env.SENDGRID_FROM ?? "",
  gasUrl: process.env.GOOGLE_APPS_SCRIPT_URL ?? "",
  appsScriptSecret: process.env.APPS_SCRIPT_SECRET ?? "",
  googleServiceAccountJson: process.env.GOOGLE_SERVICE_ACCOUNT_JSON ?? "",
  googleDriveFolderId: process.env.GOOGLE_DRIVE_FOLDER_ID ?? "",
  r2AccountId: process.env.CLOUDFLARE_R2_ACCOUNT_ID ?? "",
  r2AccessKeyId: process.env.CLOUDFLARE_R2_ACCESS_KEY_ID ?? "",
  r2SecretAccessKey: process.env.CLOUDFLARE_R2_SECRET_ACCESS_KEY ?? "",
  r2Bucket: process.env.CLOUDFLARE_R2_BUCKET ?? "",
  r2PublicUrl: process.env.CLOUDFLARE_R2_PUBLIC_URL ?? "", // e.g. https://pub-XXXX.r2.dev
};
