import { getDb } from "./db";
import { merchItems } from "../drizzle/schema";

const INITIAL_MERCH = [
  {
    sortOrder: 0,
    name: "FATUWR 2024 Checklist Shirts",
    description: "100% cotton, blue print on white\n2025 Tees are higher quality",
    memberPrice: "35 SGD (2025 shirts); 20 SGD (2024 shirts)",
    nonMemberPrice: "45 SGD / 55 AUD / 30 EUR (2025 shirts); 25 SGD / 30 AUD / 25 EUR (2024 shirts)",
    photo1: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/L0CsjyBe1wKdqueE68Pv/pub/oNJ6dChde6lHXEKFIct2.jpg",
    photo2: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/L0CsjyBe1wKdqueE68Pv/pub/rhsjsbxB72jSf7q3hrKZ.png",
    availableSizes: "3XL, 2XL, XL, L, M, S, XS",
    howToPurchase: "Please PM Darryn to confirm available size",
    inventory: "**2025 stock TBC//\n\n3XL - 9 pcs\n\n2XL - 18 pcs\n\nXL - 16 pcs\n\nL - 24 pcs\n\nM - 23 pcs\n\nS - 14 pcs; 4 pcs (2024 stock)\n\nXS - 3 pcs; 4 pcs (2024 stock)\n\nLast updated: 11-Mar-2026",
  },
  {
    sortOrder: 0.1,
    name: "FATUWR 2023/2024 SWIMSUITS (MEN)",
    description: "2023/2024 club suits (trunks). These are double lined.",
    memberPrice: "60 SGD / set",
    nonMemberPrice: "70 SGD / set",
    photo1: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/L0CsjyBe1wKdqueE68Pv/pub/wgflhFFXMdWgB73rn2Z6.jpeg",
    photo2: null,
    availableSizes: "2024: S, M, XL, 2XL\n2023: 40\"",
    howToPurchase: "Reach out to Darryn for inventory enquiries. Trunks are sold in a set (black and white) - with some exceptions for leftover inventory.\n\nPlease confirm payment ID before purchasing!",
    inventory: "2XL - 2 sets\nXL - 2 sets\nM - 2 sets\nS - 2 sets\n\n40 - 2 White, 1 Black\nXL - 1 Black, 1 White\n\n// Last updated: 4-Mar-2026",
  },
  {
    sortOrder: 0.11,
    name: "FATUWR 2023/2024 SWIMSUITS (WOMEN)",
    description: "2023/2024 club swimsuits (open back). These are single lined with a white lining.",
    memberPrice: "80 SGD / set",
    nonMemberPrice: "90 SGD / set",
    photo1: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/L0CsjyBe1wKdqueE68Pv/pub/cKIFGjFGQbCDWve11Z1H.jpeg",
    photo2: null,
    availableSizes: "2024: S, M, L, XL, 2XL\n2023: 22, 24, 26, 36",
    howToPurchase: "Reach out to Darryn for inventory enquiries. Swimsuits are sold in a set (black and white) - with some exceptions for leftover inventory.\n\nPlease confirm Payment ID before purchasing!",
    inventory: "2XL - 2 set\nXL - 2 set\nL - 2 set\nM - 1 white, 2 black\nS - 1 black\n\n36 - 1 set\n26 - 1 set, 1 black\n24 - 3 set, 1 black\n22 - 1 set\n\n// Last updated: 11-Mar-2026",
  },
  {
    sortOrder: 0.12,
    name: "FATUWR 2024 Waterpolo Caps",
    description: null,
    memberPrice: "40 SGD / set",
    nonMemberPrice: "45 SGD / set",
    photo1: null,
    photo2: null,
    availableSizes: "NA",
    howToPurchase: "Please PM Darryn to confirm inventory availability.\n\nPlease confirm payment ID before purchasing!",
    inventory: "Number on cap:\n73 - 1 set\n75 - 1 set\n79 - 1 set\n\nLast updated: 11-Mar-2026",
  },
  {
    sortOrder: 1,
    name: "FATUWR 2023 Skull Shirts",
    description: "The shirt is designed to be versatile (formal & fun).\n\nFront: Underwater rugby player — designed to let people know we play underwater rugby and showcase our sport.\n\nBack: skull design is meant to be a fun graphic tee, to catch attention and be fun. Skull is also fierce and shows that we can be competitive. Look closely at the design and you can spot the Easter egg of our fugu within the skull — a nod to our mascot the fugu!\n\n💚💚💚💚💚",
    memberPrice: "20 SGD",
    nonMemberPrice: "25 SGD / 30 AUD / 25 EUR",
    photo1: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/L0CsjyBe1wKdqueE68Pv/pub/zN4lZw3Ouw3vhyzXxTgW.jpeg",
    photo2: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/L0CsjyBe1wKdqueE68Pv/pub/0ewWOhauwDXU1zx8Mhtu.jpeg",
    availableSizes: "2XS, XS",
    howToPurchase: "Please PM Darryn to confirm inventory availability.\n\nPlease confirm payment ID before purchasing!",
    inventory: "2XS - 2 pcs\nXS - 6 pcs\n\n// Last updated: 11-Mar-2026",
  },
  {
    sortOrder: 1.1,
    name: "FATUWR 2021 Shirts",
    description: null,
    memberPrice: "20 SGD",
    nonMemberPrice: "25 SGD / 30 AUD / 25 EUR",
    photo1: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/PDgHHgL6IwTmdH6oweA8/pub/ChEsincfWIzYIMTzUMGb.jpeg",
    photo2: null,
    availableSizes: "XL",
    howToPurchase: "Please PM Darryn to confirm inventory availability.\n\nPlease confirm payment ID before purchasing.",
    inventory: "XL - 1 pc\n\nLast updated: 5-Apr-2026",
  },
  {
    sortOrder: 1.5,
    name: "Sticker sheets (2025)",
    description: "6 solvent print vinyl stickers per sheet",
    memberPrice: "$3",
    nonMemberPrice: "$4.5 / EUR 3 / AUD 6",
    photo1: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/y8PCQBDqBJ3Y1TUFLVQt/pub/08UXlQ4feC31JkJ9fy0z.jpg",
    photo2: null,
    availableSizes: "",
    howToPurchase: "PM Darryn to purchase\nConfirm payment ID before purchase",
    inventory: "86\n\n// Last updated: 11-Mar-2026",
  },
  {
    sortOrder: 2,
    name: "FATUWR 2023 washbag",
    description: null,
    memberPrice: "20 SGD",
    nonMemberPrice: "25 SGD / 25 AUD / 25 EUR",
    photo1: null,
    photo2: null,
    availableSizes: "NA",
    howToPurchase: "Please PM Darryn to confirm inventory availability.\n\nPlease confirm payment ID before purchasing!",
    inventory: "1 pcs\n\nLast updated: 11-Mar-2026",
  },
  {
    sortOrder: 6,
    name: "FATUWR polo shirt",
    description: null,
    memberPrice: "5 SGD",
    nonMemberPrice: "8 SGD",
    photo1: null,
    photo2: null,
    availableSizes: "M",
    howToPurchase: "Please PM Darryn to double check that we have size/inventory available.\n\nPlease confirm payment ID before purchasing!",
    inventory: "4 pcs\n\n// Last updated: 11-Mar-2026",
  },
  {
    sortOrder: 10,
    name: "FATUWR CAP",
    description: "Comes with the Adex Ocean Mission logo on the side. UWR on the front, FATUWR on the brim.",
    memberPrice: "25 SGD",
    nonMemberPrice: "30 SGD",
    photo1: "https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/L0CsjyBe1wKdqueE68Pv/pub/URnoTXvoFtBrVtARZk6l.jpeg",
    photo2: null,
    availableSizes: "Free size",
    howToPurchase: "Please PM Gary to confirm inventory availability.\n\nPlease confirm Payment ID before purchasing.",
    inventory: "95 pcs\n\n// Last updated: 11-Mar-2026",
  },
];

export async function seedMerchIfEmpty(): Promise<void> {
  const db = await getDb();
  if (!db) return;
  const existing = await db.select().from(merchItems).limit(1);
  if (existing.length > 0) return;
  await db.insert(merchItems).values(INITIAL_MERCH);
  console.log("[Seed] Merch items seeded:", INITIAL_MERCH.length);
}
